model_list:
  - model_name: "tngtech/deepseek-r1t2-chimera:free"
    litellm_params:
      model: "tngtech/deepseek-r1t2-chimera:free"
      timeout: 3600
      stream_timeout: 3600
- model_name: "moonshotai/kimi-k2:free"
    litellm_params:
      model: "moonshotai/kimi-k2:free"
      timeout: 3600
      stream_timeout: 3600
  - model_name: "deepseek-coder-v2-lite-instruct"
    litellm_params:
      model: "deepseek-coder-v2-lite-instruct"
      timeout: 3600
      stream_timeout: 3600
  - model_name: "qwen/qwen3-coder-30b"
    litellm_params:
      model: "qwen/qwen3-coder-30b"
      timeout: 3600
      stream_timeout: 3600
  - model_name: "phi-3-mini-128k-instruct@q5_k_m"
    litellm_params:
      model: "phi-3-mini-128k-instruct@q5_k_m"
      timeout: 3600
      stream_timeout: 3600
  - model_name: "openrouter/horizon-beta"
    litellm_params:
      model: "openrouter/horizon-beta"
      timeout: 3600
      stream_timeout: 3600
# Optional: To see detailed logs from LiteLLM
litellm_settings:
  set_verbose: True